### ISSUE TITLE
Add possibility to wait until the queue finishes

### ISSUE THREAD

**Issue by jupardo** [Maggi64/moderndash#106]
version 3.5.0

It is not possible to wait for the queue to complete all tasks unless I use the await method when queueing the task. It would be a significant improvement to wait until all the promises I've queued before finish.

**Comment by jupardo** [comment]
I've included a small example:
`import { Queue } from 'moderndash';

const promiseToTime = (time: number, value) =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(value), time);
  });

(async () => {
  let a;
  // Create a queue that can run 3 tasks concurrently
  const queue = new Queue(3);

  queue.add(async () => {
    a = await promiseToTime(2000, 'a');
  });

  queue.add(() => promiseToTime(1000, 'b'));

  queue.add([
    () => promiseToTime(3000, 'c').then((val) => (a = val)),
    () => promiseToTime(0, 'd'),
  ]);
  console.log(a); // undefined
  queue.magicFunction()
  console.log(a); // 'a'
})();
`

**Comment by Maggi64** [comment]
@jupardo @chris-feist how about this? https://github.com/Maggi64/moderndash/pull/107

**Comment by chris-feist** [comment]
LGTM. Although its not clear from the docs how rejections are handled for `Queue.add` and `Queue.done`, so a minor suggestion would be to update that too
