### ISSUE TITLE
Shouldn't `hotscript` be in the main dependencies since it's imported in `dist/index.d.ts`?

### ISSUE THREAD

**Issue by eych** [Maggi64/moderndash#117]
Hello!

I'm probably missing something, but I'm getting an error during my TS build because `dist/index.d.ts` from `moderndash` imports from `hotscript`, but it's not installed as a dependency — it's listed in `devDependencies` instead, so it's not in my project at all as a result, although I've run `npm install moderndash` previously.

The line at the very top of `dist/index.d.ts`

```typescript
import { Call, Tuples, Objects } from 'hotscript';
```

Should `hotscript` be moved to the main dependencies instead?

**Comment by Maggi64** [comment]
Thank you for the report, having the import there is not intended. It should bundle the definitions. I will look into that.

**Comment by Maggi64** [comment]
I couldn't get tsup, esbuild to bundle the hotscript dependency into the d.ts file. I moved `hotscript` to dependencies for now.
