### ISSUE TITLE
Feature request: debounce.pending()

### ISSUE THREAD

**Issue by tkrotoff** [Maggi64/moderndash#135]
Add `pending` function to `debounce`

<br>

Here the issue on Lodash (2017/09): https://github.com/lodash/lodash/issues/3387
The PR that implements it (2017/09, jdalton himself): https://github.com/lodash/lodash/pull/3388

It is present in Lodash master (2017/09, 6 years ago):
- https://github.com/lodash/lodash/blob/master/debounce.js#L62C1-L63
- https://github.com/lodash/lodash/blob/master/debounce.js#L180-L182

And yet never published as a Lodash npm package:
- https://github.com/lodash/lodash/blob/4.17.21/lodash.js#L10372
- https://stackoverflow.com/a/50822291
- https://github.com/lodash/lodash/issues/5146
- https://github.com/lodash/lodash/issues/4322

It should be part of Lodash v5 (which will probably never come)

Other interesting issues related to debounce.pending():
- https://github.com/lodash/lodash/issues/5633
- https://github.com/lodash/lodash/issues/2618
- https://github.com/lodash/lodash/issues?q=debounce+pending

**Comment by Maggi64** [comment]
Hi, surely a good addition!
But I don't know when I will find the time to do this. A PR would be appreciated!

**Comment by Maggi64** [comment]
Released in 3.8.0!
