### ISSUE TITLE
Return the result of the last `throttle` invocation

### ISSUE THREAD

**Issue by iSplasher** [Maggi64/moderndash#140]
Hi, lodash has this property with its `throttle` function that I think is more useful to be the default.
> The func is invoked with the last arguments provided to the throttled function. Subsequent calls to the throttled function return the result of the last func invocation. 

What do you say?

**Comment by Maggi64** [comment]
Definitely something that should be done, I agree

**Comment by iSplasher** [comment]
`debounce` has the same property
