### ISSUE TITLE
PlainObject not working with Interfaces

### ISSUE THREAD

**Issue by Kagu-chan** [Maggi64/moderndash#142]
The Type `PlainObject`, which is used as type constrain for functions like `merge` does not accept interfaces.

```typescript
type R = Record<PropertyKey, unknown>; // same as PlainObject, but its not exported. So lets rebuild it here
type Foo = {
  a: number;
  b: number;
};
interface Boo {
  a: number;
  b: number;
}

function f<x extends R>(x: x): void {
  /* NOP */
}

f<Foo>({ a: 1, b: 1 }); // This is OK
f<Boo>({ a: 1, b: 1 }); // This fails and requires a symbol and a string key

/*
Type 'Boo' does not satisfy the constraint 'R'.
  Index signature for type 'string' is missing in type 'Boo'.ts(2344)
*/
```

TS Playground: https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBASlC8sIGMD2AnAJgHgArtUnVAGkIQAaKAVwDsBrW1Ad1oD4BuKAem6gGcAhgFtog-lFwAbQQEtaAeQBGAKxTAqS6sCizgEpjogAPMBmARMAOigBlVFCkR9UdBC2ypmXToAWENwBYAChQSCgAMVQHRABvEKgoQQAuKFpqYSUAjgSoJVT0zOyQgF8c4PkLdAAzQWRoACFoqHjgxJS0jKz0csT8zqKe0pCQ6rpkYFlUWihq7GMoEwtaTAkYNgAKY1TjAEpUgDdUWW9WxO4AKigAOQVcKAvuYeDR7CjUTdik1IBGTV+oCVdlxeFAACq+WQSKFQBQkV5ND4bL4dP55AFAkF8CEw2qeCSCFauCAAR2osjcBIEIEyqCkSSJggEwHQ8gA5lB6OQgA

**Comment by kemaric** [comment]
I can take a look into this.

**Comment by Maggi64** [comment]
🤔 I've tried a few things but haven't found a good solution. If anyone has a good solution, please let me know.

**Comment by Maggi64** [comment]
Making use of  `Record<PropertyKey, any>` fixes it. And will be released shortly. The tradeoff is that now other objects like Date, RegEx also can be passed into the function. I think this is better then dealing with TS when using interfaces.

https://github.com/Maggi64/moderndash/commit/bc9aeec716edd3a717b001f2e475bd7664e45cbd
