### ISSUE TITLE
Feature request - Array/concat

### ISSUE THREAD

**Issue by ForeverGuo** [Maggi64/moderndash#163]
https://lodash.com/docs/4.17.15#concat

**Comment by ForeverGuo** [comment]
how to push my code ?

**Comment by Maggi64** [comment]
Since this can be easy done with [...array1, ...array2] there is no need to add this.

**Comment by ForeverGuo** [comment]
ok  fill is be need ?  https://lodash.com/docs/4.17.15#fill

**Comment by ForeverGuo** [comment]
I thought it was exactly the same as lodash

**Comment by Maggi64** [comment]
If the function can be easily replaced by native JS functions it makes no sense to include this.
See: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore?tab=readme-ov-file#_fill
