### ISSUE TITLE
Feature request - clone

### ISSUE THREAD

**Issue by ForeverGuo** [Maggi64/moderndash#166]
https://lodash.com/docs/4.17.15#cloneDeep

**Comment by ForeverGuo** [comment]
https://lodash.com/docs/4.17.15#pick  ？

**Comment by Maggi64** [comment]
Both can be easily replaced by native javascript i.e `structuredClone`.

I added more info to the FAQ, that should clarify the use case for this lib.
https://github.com/Maggi64/moderndash?tab=readme-ov-file#why-is-x-lodash-function-not-included

**Comment by ForeverGuo** [comment]
ok
