### ISSUE TITLE
Suggestion: Difference function marked deprecated but instead should be a recommendation

### ISSUE THREAD

**Issue by MatthewAry** [Maggi64/moderndash#182]
The ergonomics of [Set.prototype.difference()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference) just is not the same as what is currently provided by moderndash. 

For example, I have code that looks like this:
```ts
const missingOrgs = difference(resolvedTenantOrgs, currentUserOrgs, (a, b) => a.id === b.id)
```
And I don't see a path for me to use the [Set.prototype.difference()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference) built-in to do this elegantly:
```ts
const missingOrgs = Array.from(
  new Set(resolvedTenantOrgs).difference(
    new Set(currentUserOrgs.map(org => org.id))
  )
).map(id => resolvedTenantOrgs.find(org => org.id === id)!);
```

I prioritize DX quite a bit, and seeing this marked as deprecated is understandable, but I believe that it would be better for moderndash to recommend users to move to  [Set.prototype.difference()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference) but not deprecate. moderndash could also refactor the current implementation of it's `difference` function to use  [Set.prototype.difference()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference) with a graceful fallback if the runtime is missing the built-in.

**Comment by Maggi64** [comment]
Your reasoning makes sense, I will replace the deprecation with a simple comment to point people the `Set.difference. In the next major version I will review the topic again.
