### ISSUE TITLE
Add noop function

### ISSUE THREAD

**Issue by tkrotoff** [Maggi64/moderndash#37]
Lodash features a noop (no operation) function: https://lodash.com/docs/4.17.15#noop

```TypeScript
export function noop() {
  // Do nothing
}
```

**Comment by Maggi64** [comment]
I thought about adding this, but since there is an easy native replacement I decided against it.
 ```ts
const noop = () => {}
```

**Comment by tkrotoff** [comment]
I understand.

However I think it is "mandatory" to add `noop` because it is already a "standard"

- https://github.com/search?l=JavaScript&q=noop+import+lodash&type=Code => 279,154 code results
- https://github.com/search?l=TypeScript&q=noop+import+lodash&type=Code => 13,468 code results
- My personal experience: all front projects I've seen in the last 2 companies I worked for used `import { noop } from 'lodash'` (not introduced by me, already in place before I joined)

I believe most JS developers are familiar with `noop` and expect it from a library like lodash or similar.

**Comment by Maggi64** [comment]
@tkrotoff Interesting points 🤔 
If there is more demand for it, I will add it.
Maybe I will do a category in github discussions. So people can upvote functions they want to see included.
I want to avoid situations of cluttered documentation like we have in https://stdlib.io/docs/api/latest

One of the packages goals is to encourage native JS where possible. That is why I am reluctant to add it right away.
