### ISSUE TITLE
Feature Request - objectKeys - typed Object.keys(obj)

### ISSUE THREAD

**Issue by bkniffler** [Maggi64/moderndash#43]
Great library! Would you consider a feature that has no runtime advantage, but improves typings? 

Similar to https://github.com/sindresorhus/ts-extras/blob/main/source/object-keys.ts
```
export type ObjectKeys<T extends object> = `${Exclude<keyof T, symbol>}`;
export const objectKeys = Object.keys as <Type extends object>(value: Type) => Array<ObjectKeys<Type>>;
```

**Comment by Maggi64** [comment]
Thank you 👍I am happy that you like it.
After thinking about it, I decided to leave that to other libraries like:
- https://github.com/total-typescript/ts-reset
- https://github.com/sindresorhus/ts-extras

Moderndash goal is to encourage native JS where possible. Alias functions seem not to fit quite into this.
Also it seems that there are edgecases where the type would not align properly.
https://github.com/total-typescript/ts-reset#objectkeysobjectentries

If this issue gets raised more often in the future I will reconsider it though.
