### ISSUE TITLE
data-first or data-last paradigm

### ISSUE THREAD

**Issue by azhiv** [Maggi64/moderndash#66]
It's not stated in the docs whether you follow data-first or data-last paradigm, but I noticed that you incline towards the latter, e.g. [intersection](https://moderndash.io/docs/intersection) and [difference](https://moderndash.io/docs/difference). At the same time [unique](https://moderndash.io/docs/unique) follows the data-first approach.
Do you have an opinion on what is better and why?
As far as I can judge from the TS perspective it's usually easier to put the callback last because all the typings would be in-place. Otherwise, when you provide the first parameter the types of the arrays are not yet defined which causes inconvenience.
Anyway, following a single paradigm seems a good way to go. What are your thoughts about it?

**Comment by azhiv** [comment]
This is super cool! Thank you for the rapid reaction on this. Looks awesome to me!

**Comment by azhiv** [comment]
This may seem a dumb question but do you really need the node version to be at least 16.15? I know I already asked you about node 19 on Reddit (and you did a great job lowering the upper bound), but your docs now claim the lowest version to be 16.14 whereas npm complains during installing:
`error moderndash@3.0.0: The engine "node" is incompatible with this module. Expected version ">=16.15". Got "16.14.2"`

**Comment by Maggi64** [comment]
Thank you! 👍 

Node did only include the global crypto object in 16.15. So this is a hard requirement to be able to use the crypto functions. https://nodejs.dev/en/api/v16/cli/#--experimental-global-webcrypto

> ![image](https://user-images.githubusercontent.com/20517052/225345844-becd3321-fa00-4817-9391-e50896227425.png)

The docs say `>16.14` , I did clarify this to `>=16.15` just now.
`globalThis.crypto = require('crypto').webcrypto;` Could be a workaround for you to still make it work with versions below 16.15

**Comment by azhiv** [comment]
Oh, I see. In fact we have a plan to upgrade our node to the latest 16.x, hopefully it will happen some time soon. Thank you for your efforts!
